support to encrypt posts by tags with the password separately
MikeCoder/hexo-blog-encrypt pull request #103
Opened 2019-09-01 17:23 UTC by SNBQT

# PR

## Proposed Changes

添加支持设置标签加密，文章设置的password优先级最高，其次是设置标签加密，各标签加密密码优先级跟文章的先后顺序有关

@MikeCoder

2019-09-01 17:31 UTC, SNBQT commented
添加支持设置标签加密，文章设置的password优先级最高，其次是设置标签加密，文章多标签加密密码优先级跟文章标签先后顺序有关

2019-09-02 06:28 UTC, D0n9X1n requested changes
功能很棒！感谢！

麻烦按要求改一下，感谢！

2019-09-02 06:28 UTC, MikeCoder commented on ReadMe.zh.md
> +  tags:  # encrypt posts by tags with the password separately
这边改成中文注释

2019-09-02 06:28 UTC, MikeCoder commented on index.js
> +  var tag1,tag2;
tag1 改成 currentTag
tag2 改成 needToEncryptTag

2019-09-02 06:28 UTC, MikeCoder commented on index.js
> +    for(var i in data.tags.data){
注意一下代码格式。

使用 [editorconfig](https://editorconfig.org/) 格式化代码。

2019-09-02 06:28 UTC, MikeCoder commented
@xiazeyu 这个功能可以在 v3.0 里面加上。

2019-09-02 07:22 UTC, SNBQT commented
相关修改已经更新

2019-09-02 07:22 UTC, D0n9X1n approved these changes

2019-09-02 07:22 UTC, merged

2019-09-02 12:08 UTC, xiazeyu commented on index.js
> +    for (var i in data.tags.data) {
hexo.config.encrypt.tags((cTag) => {
  if(data.tags.includes(cTag.name))
    data.password = data.password || cTag.password;
})

这样可读性大概更强一点...
话说为什么要去找data.tags里的data[].name啊orz 文档头的标签不应该表现为字符串数组嘛orz

2019-09-02 12:17 UTC, xiazeyu commented on index.js
> +    for (var i in data.tags.data) {
然后...能不用label就尽量别用吧...
学C++的时候一直被教导这玩意很毒瘤..
现在也有很多替代了

2019-09-02 13:35 UTC, MikeCoder commented on index.js
> +    for (var i in data.tags.data) {
data.tags 并不是字符串数组啊。。是一个这样的结构:
```
Query {
  data: [
    Document {
      name: 'test',
      _id: 'ck02fz3hu000aunf4grqujuz0',
      slug: [Getter],
      path: [Getter],
      permalink: [Getter],
      posts: [Getter],
      length: [Getter]
    },
    Document {
      name: 'fff',
      _id: 'ck02fz3hv000bunf4wtzr7bgz',
      slug: [Getter],
      path: [Getter],
      permalink: [Getter],
      posts: [Getter],
      length: [Getter]
    }
  ],
  length: 2
}
```

如果这边是多重循环的话，我觉得 goto 还是可以接受的，如果是用 lambda，那就可以干掉了。

2019-09-02 13:56 UTC, MikeCoder commented on index.js
> +    for (var i in data.tags.data) {
这里其实有个 bug，如果 data.tags 为空，也就是不设置 tags，那么会有个空异常。。。review 没看出来，还是太弱了。（允悲）

2019-09-02 14:45 UTC, SNBQT commented on index.js
> +    for (var i in data.tags.data) {
> 这里其实有个 bug，如果 data.tags 为空，也就是不设置 tags，那么会有个空异常。。。review 没看出来，我还是太弱了。（允悲）

我当时考虑了tags为空异常，测试了hexo.config.encrypt里tags为空，漏测试data里的了(ノへ￣、)捂脸